using System.Globalization;
using System.Text;

namespace Lvgl.Ui;

/// <summary>
/// Emits C# that rebuilds a <see cref="UiDocument"/> with the LVGL.Net widget API.
/// </summary>
/// <remarks>
/// <para>
/// The generated type is <c>partial</c> and calls a <c>partial void OnBuilt()</c> hook at the end
/// of <c>Build</c>. Application code puts event wiring and data binding in the other half of the
/// class, so regenerating the layout never overwrites hand-written logic.
/// </para>
/// <para>
/// This produces a file to check in, not a compiler source generator: designer output is edited
/// through the designer, and having the code on disk keeps the build free of extra tooling.
/// </para>
/// </remarks>
public sealed class CSharpUiGenerator
{
    /// <summary>Namespace for the generated class. Omitted when null or empty.</summary>
    public string? Namespace { get; set; }

    /// <summary>Class name; defaults to the document name.</summary>
    public string? ClassName { get; set; }

    /// <summary>Access modifier of the generated class.</summary>
    public string AccessModifier { get; set; } = "public";

    /// <summary>Source file the code was generated from, mentioned in the header comment.</summary>
    public string? SourcePath { get; set; }

    /// <summary>
    /// Generates the C# source text.
    /// </summary>
    /// <exception cref="InvalidOperationException">The document has validation problems.</exception>
    public string Generate(UiDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var problems = document.Validate();
        if (problems.Count > 0)
        {
            throw new InvalidOperationException(
                "The layout cannot be generated until these problems are fixed:" +
                Environment.NewLine + string.Join(Environment.NewLine, problems.Select(p => "  - " + p)));
        }

        var className = Sanitize(ClassName ?? document.Name, "Screen");
        var writer = new IndentedWriter();

        writer.Line("// <auto-generated />");
        writer.Line(SourcePath is null
            ? "// Generated by the LVGL.Net designer. Do not edit; regenerate instead."
            : $"// Generated by the LVGL.Net designer from {Path.GetFileName(SourcePath)}. Do not edit; regenerate instead.");
        writer.Line("// Event handlers and data binding belong in the other half of this partial class.");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line("using Lvgl;");
        writer.Line("using Lvgl.Drawing;");
        writer.Line("using Lvgl.Widgets;");
        writer.Line();

        if (!string.IsNullOrWhiteSpace(Namespace))
        {
            writer.Line($"namespace {Namespace};");
            writer.Line();
        }

        writer.Line($"/// <summary>Layout '{Escape(document.Name)}', generated from a designer document.</summary>");
        writer.Line($"{AccessModifier} partial class {className}");
        writer.OpenBrace();

        writer.Line("/// <summary>Width the layout was designed against.</summary>");
        writer.Line($"public const int DesignWidth = {document.Width};");
        writer.Line();
        writer.Line("/// <summary>Height the layout was designed against.</summary>");
        writer.Line($"public const int DesignHeight = {document.Height};");
        writer.Line();
        writer.Line("/// <summary>The container the layout was built into.</summary>");
        writer.Line("public LvObject Root { get; private set; } = null!;");
        writer.Line();

        var named = document.Descendants().Where(n => !string.IsNullOrEmpty(n.Name)).ToList();
        foreach (var node in named)
        {
            writer.Line($"/// <summary>The {node.Type} named '{Escape(node.Name!)}'.</summary>");
            writer.Line($"public {TypeName(node.Type)} {node.Name} {{ get; private set; }} = null!;");
            writer.Line();
        }

        writer.Line("/// <summary>Creates every widget of the layout.</summary>");
        writer.Line("/// <param name=\"parent\">Container to build into; null uses the active screen.</param>");
        writer.Line("public LvObject Build(LvObject? parent = null)");
        writer.OpenBrace();
        writer.Line("Root = parent ?? LvScreen.Active();");

        if (TryColorLiteral(document.BackgroundColor, out var screenBackground))
        {
            writer.Line($"Root.SetBackgroundColor({screenBackground});");
        }

        var names = new UniqueNames();
        foreach (var node in document.Children)
        {
            writer.Line();
            Emit(writer, node, "Root", names);
        }

        writer.Line();
        writer.Line("OnBuilt();");
        writer.Line("return Root;");
        writer.CloseBrace();

        writer.Line();
        writer.Line("/// <summary>Called once the layout has been built. Implement it in your own partial half.</summary>");
        writer.Line("partial void OnBuilt();");

        writer.CloseBrace();

        return writer.ToString();
    }

    private void Emit(IndentedWriter writer, UiNode node, string parentExpression, UniqueNames names)
    {
        var local = names.Next(node);

        writer.Line($"var {local} = {Construct(node, parentExpression)};");

        if (node.Width is { } width && node.Height is { } height)
        {
            writer.Line($"{local}.SetSize({width}, {height});");
        }
        else
        {
            if (node.Width is { } onlyWidth) writer.Line($"{local}.Width = {onlyWidth};");
            if (node.Height is { } onlyHeight) writer.Line($"{local}.Height = {onlyHeight};");
        }

        if (node.Align is { } align) writer.Line($"{local}.Align(LvAlign.{align}, {node.X}, {node.Y});");
        else writer.Line($"{local}.SetPosition({node.X}, {node.Y});");

        EmitProperties(writer, node, local);

        if (!string.IsNullOrEmpty(node.Name)) writer.Line($"{node.Name} = {local};");

        foreach (var child in node.Children)
        {
            writer.Line();
            Emit(writer, child, local, names);
        }
    }

    private static void EmitProperties(IndentedWriter writer, UiNode node, string local)
    {
        if (TryColorLiteral(node.BackgroundColor, out var background)) writer.Line($"{local}.SetBackgroundColor({background});");
        if (TryColorLiteral(node.TextColor, out var text)) writer.Line($"{local}.SetTextColor({text});");
        if (TryColorLiteral(node.BorderColor, out var border)) writer.Line($"{local}.SetBorderColor({border});");

        if (node.BorderWidth is { } borderWidth) writer.Line($"{local}.SetBorderWidth({borderWidth});");
        if (node.Radius is { } radius) writer.Line($"{local}.SetRadius({radius});");
        if (node.Padding is { } padding) writer.Line($"{local}.SetPadding({padding});");
        if (node.FontSize is { } fontSize) writer.Line($"{local}.SetFontSize({fontSize});");

        switch (node.Type)
        {
            case UiWidgetType.Slider or UiWidgetType.Bar:
                if (node.Minimum is { } min && node.Maximum is { } max) writer.Line($"{local}.SetRange({min}, {max});");
                if (node.Value is { } value) writer.Line($"{local}.SetValue({value}, animate: false);");
                break;

            case UiWidgetType.Arc:
                if (node.Minimum is { } arcMin && node.Maximum is { } arcMax) writer.Line($"{local}.SetRange({arcMin}, {arcMax});");
                if (node.Value is { } arcValue) writer.Line($"{local}.Value = {arcValue};");
                break;

            case UiWidgetType.Chart:
                if (node.ChartType is { } chartType) writer.Line($"{local}.Type = LvChartType.{chartType};");
                if (node.PointCount is { } points and > 0) writer.Line($"{local}.PointCount = {points};");
                if (node.Minimum is { } chartMin && node.Maximum is { } chartMax)
                {
                    writer.Line($"{local}.SetRange(LvChartAxis.PrimaryY, {chartMin}, {chartMax});");
                }
                foreach (var series in node.SeriesColors)
                {
                    TryColorLiteral(series, out var literal);
                    writer.Line($"{local}.AddSeries({literal ?? "LvColor.Blue"});");
                }
                break;
        }

        if (node.Hidden) writer.Line($"{local}.IsHidden = true;");
    }

    private static string Construct(UiNode node, string parent) => node.Type switch
    {
        UiWidgetType.Panel => $"new LvPanel({parent})",
        UiWidgetType.Label => $"new LvLabel({parent}, {Literal(node.Text)})",
        UiWidgetType.Button => $"new LvButton({parent}, {Literal(node.Text)})",
        UiWidgetType.Slider => $"new LvSlider({parent})",
        UiWidgetType.Bar => $"new LvBar({parent})",
        UiWidgetType.Arc => $"new LvArc({parent})",
        UiWidgetType.Switch => $"new LvSwitch({parent}) {{ IsOn = {Bool(node.Value is > 0)} }}",
        UiWidgetType.Checkbox => $"new LvCheckbox({parent}, {Literal(node.Text)}) {{ IsChecked = {Bool(node.Value is > 0)} }}",
        UiWidgetType.Dropdown => $"new LvDropdown({parent}) {{ Options = {StringArray(node.Options)} }}",
        UiWidgetType.Roller => $"new LvRoller({parent}) {{ Options = {StringArray(node.Options)} }}",
        UiWidgetType.TextArea => $"new LvTextArea({parent}) {{ Text = {Literal(node.Text)} }}",
        UiWidgetType.Chart => $"new LvChart({parent})",
        _ => throw new NotSupportedException($"Unknown widget type {node.Type}."),
    };

    internal static string TypeName(UiWidgetType type) => type switch
    {
        UiWidgetType.Panel => "LvPanel",
        UiWidgetType.Label => "LvLabel",
        UiWidgetType.Button => "LvButton",
        UiWidgetType.Slider => "LvSlider",
        UiWidgetType.Bar => "LvBar",
        UiWidgetType.Arc => "LvArc",
        UiWidgetType.Switch => "LvSwitch",
        UiWidgetType.Checkbox => "LvCheckbox",
        UiWidgetType.Dropdown => "LvDropdown",
        UiWidgetType.Roller => "LvRoller",
        UiWidgetType.TextArea => "LvTextArea",
        UiWidgetType.Chart => "LvChart",
        _ => "LvObject",
    };

    private static bool TryColorLiteral(string? text, out string? literal)
    {
        literal = null;
        if (string.IsNullOrWhiteSpace(text) || !Drawing.LvColor.TryParse(text, out var color)) return false;

        literal = $"LvColor.FromRgb(0x{color.Rgb:X6}u)";
        return true;
    }

    private static string Bool(bool value) => value ? "true" : "false";

    private static string StringArray(IReadOnlyList<string> values) =>
        values.Count == 0 ? "[]" : "[" + string.Join(", ", values.Select(Literal)) + "]";

    private static string Literal(string? value) => value is null ? "\"\"" : "\"" + Escape(value) + "\"";

    private static string Escape(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\r", "\\r", StringComparison.Ordinal)
        .Replace("\n", "\\n", StringComparison.Ordinal);

    private static string Sanitize(string name, string fallback)
    {
        var builder = new StringBuilder(name.Length);
        foreach (var c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_') builder.Append(c);
        }

        if (builder.Length == 0) return fallback;
        if (char.IsDigit(builder[0])) builder.Insert(0, '_');

        return builder.ToString();
    }

    /// <summary>Allocates a unique, readable local variable name for each emitted widget.</summary>
    private sealed class UniqueNames
    {
        private readonly HashSet<string> _used = new(StringComparer.Ordinal);
        private int _counter;

        public string Next(UiNode node)
        {
            var seed = string.IsNullOrEmpty(node.Name)
                ? node.Type.ToString()
                : Sanitize(node.Name, node.Type.ToString());

            var candidate = char.ToLowerInvariant(seed[0]) + seed[1..];

            // A local that collides with the generated property of the same node would shadow it.
            if (string.Equals(candidate, node.Name, StringComparison.Ordinal)) candidate += "Widget";

            while (!_used.Add(candidate))
            {
                candidate = string.Create(CultureInfo.InvariantCulture, $"{seed.ToLowerInvariant()}{++_counter}");
            }

            return candidate;
        }
    }

    /// <summary>Minimal brace-aware writer, so the generated file is readable as checked-in source.</summary>
    private sealed class IndentedWriter
    {
        private readonly StringBuilder _builder = new(4096);
        private int _depth;

        public void Line(string text = "")
        {
            if (text.Length > 0) _builder.Append(' ', _depth * 4);
            _builder.AppendLine(text);
        }

        public void OpenBrace()
        {
            Line("{");
            _depth++;
        }

        public void CloseBrace()
        {
            _depth--;
            Line("}");
        }

        public override string ToString() => _builder.ToString();
    }
}
