// Builds the .NET Interactive notebooks in /notebooks from the definitions below, and a verification
// program per notebook (tools/notebooks/verify/*.cs) that runs the same code cells as a .NET 10
// file-based app. Notebooks cannot be executed in CI without Jupyter; the verification programs can.
//
//   node tools/notebooks/build.mjs
//   dotnet run tools/notebooks/verify/01-getting-started.cs
//
// Code cells marked { decl: true } declare types; they are moved to the end of the verification
// program because C# requires top-level statements to come first.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { notebooks } from "./notebooks.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const version = "0.1.0";

const packages = {
  core: "Gravicode.ScrapyNet",
  sandbox: "Gravicode.ScrapyNet.Sandbox",
  ai: "Gravicode.ScrapyNet.AI",
  platform: "Gravicode.ScrapyNet.Platform",
};
const projects = {
  core: "src/ScrapyNet.Core/ScrapyNet.Core.csproj",
  sandbox: "src/ScrapyNet.Sandbox/ScrapyNet.Sandbox.csproj",
  ai: "src/ScrapyNet.AI/ScrapyNet.AI.csproj",
  platform: "src/ScrapyNet.Platform/ScrapyNet.Platform.csproj",
};

const lines = (s) => s.replace(/^\n/, "").replace(/\n$/, "").split("\n").map((l, i, a) => (i < a.length - 1 ? l + "\n" : l));

function codeCell(source) {
  return {
    cell_type: "code",
    execution_count: null,
    metadata: { dotnet_interactive: { language: "csharp" }, polyglot_notebook: { kernelName: "csharp" } },
    outputs: [],
    source: lines(source),
  };
}

function markdownCell(source) {
  return { cell_type: "markdown", metadata: {}, source: lines(source) };
}

mkdirSync(join(root, "notebooks"), { recursive: true });
mkdirSync(join(root, "tools", "notebooks", "verify"), { recursive: true });

for (const nb of notebooks) {
  const refs = nb.packages.map((p) => `#r "nuget: ${packages[p]}, ${version}"`).join("\n");
  const setup = `// Packages / Paket
${refs}

// Before the packages are on nuget.org, point at a local build instead:
//   dotnet pack ScrapyNet.slnx -c Release -o artifacts
// and add this line above the #r lines:  #i "nuget: ../artifacts"`;

  const cells = [
    markdownCell(`# ${nb.title}\n\n${nb.intro}\n\n*Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.*`),
    codeCell(setup),
    ...nb.cells.map((c) => (c.md !== undefined ? markdownCell(c.md) : codeCell(c.code))),
  ];

  const notebook = {
    cells,
    metadata: {
      kernelspec: { display_name: ".NET (C#)", language: "C#", name: ".net-csharp" },
      language_info: { name: "polyglot-notebook" },
      polyglot_notebook: { kernelInfo: { defaultKernelName: "csharp", items: [{ aliases: [], name: "csharp" }] } },
    },
    nbformat: 4,
    nbformat_minor: 5,
  };
  writeFileSync(join(root, "notebooks", `${nb.file}.ipynb`), JSON.stringify(notebook, null, 1) + "\n");

  // Verification program.
  const codeCells = nb.cells.filter((c) => c.code !== undefined);
  const usings = new Set();
  const body = [];
  const decls = [];
  for (const c of codeCells) {
    const kept = [];
    for (const line of c.code.split("\n")) {
      if (/^using [A-Za-z0-9_.]+;$/.test(line.trim())) usings.add(line.trim());
      else kept.push(line);
    }
    (c.decl ? decls : body).push(kept.join("\n"));
  }
  const program = [
    `// Generated by tools/notebooks/build.mjs from notebooks/${nb.file}.ipynb — do not edit.`,
    ...nb.packages.map((p) => `#:project ../../../${projects[p]}`),
    "#:property TreatWarningsAsErrors=false",
    "",
    ...[...usings].sort(),
    "",
    "static void display(object? value) => Console.WriteLine(value is System.Collections.IEnumerable e && value is not string ? string.Join(\"\\n\", e.Cast<object?>()) : value);",
    "",
    ...body,
    "",
    ...decls,
    "",
  ].join("\n");
  writeFileSync(join(root, "tools", "notebooks", "verify", `${nb.file}.cs`), program);
  console.log(`built ${nb.file}`);
}
