// Generated by tools/notebooks/build.mjs from notebooks/01-getting-started.ipynb — do not edit.
#:project ../../../src/ScrapyNet.Core/ScrapyNet.Core.csproj
#:property TreatWarningsAsErrors=false

using ScrapyNet.Cmdline;
using ScrapyNet;

static void display(object? value) => Console.WriteLine(value is System.Collections.IEnumerable e && value is not string ? string.Join("\n", e.Cast<object?>()) : value);


var response = await Fetcher.FetchAsync("https://quotes.toscrape.com/");
display($"{response.Status} {response.Url} ({response.Body.Length:N0} bytes)");
display(response.Css("title::text").Get());
display(response.Css("small.author::text").GetAll().Distinct());
display(response.Xpath("//div[@class='quote'][1]//a[@class='tag']/text()").GetAll());
display(response.Css("span.text::text").ReFirst(@"“(\w+)"));
var settings = new Settings();
settings.Set(SettingKeys.LogLevel, "WARNING");
settings.Set(SettingKeys.CloseSpiderPageCount, 2);   // be polite: two pages are enough here
settings.Set(SettingKeys.DownloadDelay, 0.5);

var (result, items) = await Scrapy.CrawlAndCollectAsync(new QuotesSpider(), settings);
display(result);
display(items.Take(3).Select(i => ItemAdapter.For(i).ToString()));

public sealed class QuotesSpider : Spider
{
    public override string Name => "quotes";
    public override IReadOnlyList<string> StartUrls => ["https://quotes.toscrape.com/"];

    public override async IAsyncEnumerable<object> Parse(Response response)
    {
        foreach (var quote in response.Css("div.quote"))
            yield return new
            {
                Text = quote.Css("span.text::text").Get(),
                Author = quote.Css("small.author::text").Get(),
                Tags = quote.Css("a.tag::text").GetAll(),
            };

        if (response.Css("li.next a::attr(href)").Get() is { } next)
            yield return response.Follow(next, Parse);
        await Task.CompletedTask;
    }
}
