// Generated by tools/notebooks/build.mjs from notebooks/03-crawlspider-and-exports.ipynb — do not edit.
#:project ../../../src/ScrapyNet.Core/ScrapyNet.Core.csproj
#:property TreatWarningsAsErrors=false

using ScrapyNet;

static void display(object? value) => Console.WriteLine(value is System.Collections.IEnumerable e && value is not string ? string.Join("\n", e.Cast<object?>()) : value);


var output = Path.Combine(Path.GetTempPath(), "scrapynet-books");
Directory.CreateDirectory(output);
var settings = new Settings();
settings.Set(SettingKeys.LogLevel, "WARNING");
settings.Set(SettingKeys.CloseSpiderItemCount, 10);   // a small sample of the catalogue
settings.Set(SettingKeys.DownloadDelay, 0.25);
settings.Feeds.Add(Path.Combine(output, "books.csv"), new FeedOptions { Overwrite = true });
settings.Feeds.Add(Path.Combine(output, "books.jsonl"), new FeedOptions { Overwrite = true });

var result = await Scrapy.CrawlAsync(new BooksSpider(), settings);
display(result);
display(File.ReadLines(Path.Combine(output, "books.csv")).Take(4));


public sealed class BooksSpider : CrawlSpider
{
    public override string Name => "books";
    public override IReadOnlyList<string> AllowedDomains => ["books.toscrape.com"];
    public override IReadOnlyList<string> StartUrls => ["https://books.toscrape.com/"];

    protected override IReadOnlyList<Rule> Rules =>
    [
        new(new LinkExtractor { RestrictCss = ["article.product_pod h3"] }, ParseBook),
    ];

    private IEnumerable<object> ParseBook(Response r)
    {
        yield return new
        {
            Title = r.Css("div.product_main h1::text").Get(),
            Price = ScrapyNet.Loaders.Transforms.Price(r.Css("p.price_color::text").Get()),
            Stock = ScrapyNet.Loaders.Transforms.ToInt(r.Css("p.availability").GetText()),
            Upc = r.Xpath("//th[text()='UPC']/following-sibling::td/text()").Get(),
        };
    }
}
