// Generated by tools/notebooks/build.mjs from notebooks/04-sandbox-practice.ipynb — do not edit.
#:project ../../../src/ScrapyNet.Core/ScrapyNet.Core.csproj
#:project ../../../src/ScrapyNet.Sandbox/ScrapyNet.Sandbox.csproj
#:property TreatWarningsAsErrors=false

using ScrapyNet.Sandbox;
using ScrapyNet;

static void display(object? value) => Console.WriteLine(value is System.Collections.IEnumerable e && value is not string ? string.Join("\n", e.Cast<object?>()) : value);


var site = await SandboxSite.StartAsync();
display(site.BaseUrl);

var quiet = new Settings();
quiet.Set(SettingKeys.LogLevel, "WARNING");
quiet.Set(SettingKeys.StatsDump, false);
var (_, account) = await Scrapy.CrawlAndCollectAsync(new LoginSpider(site.Url("/login")), quiet);
display(ItemAdapter.For(account[0]));
var flaky = await ScrapyNet.Cmdline.Fetcher.FetchAsync(site.Url($"/flaky/{Guid.NewGuid():N}?fail=2"));
display($"{flaky.Status} after {flaky.Request.Meta.GetValueOrDefault(MetaKeys.RetryTimes)} retries");
await site.DisposeAsync();

public sealed class LoginSpider(string url) : Spider
{
    public override IReadOnlyList<string> StartUrls => [url];

    public override async IAsyncEnumerable<object> Parse(Response response)
    {
        yield return FormRequest.FromResponse(response,
            [new("username", SandboxSite.Username), new("password", SandboxSite.Password)],
            callback: Account);
        await Task.CompletedTask;
    }

    private IEnumerable<object> Account(Response r)
    {
        yield return new { Welcome = r.Css("h1.welcome::text").Get(), Orders = r.Css("li.order").Count };
    }
}
