// Generated by tools/notebooks/build.mjs from notebooks/05-ai-rag.ipynb — do not edit.
#:project ../../../src/ScrapyNet.Core/ScrapyNet.Core.csproj
#:project ../../../src/ScrapyNet.Sandbox/ScrapyNet.Sandbox.csproj
#:project ../../../src/ScrapyNet.AI/ScrapyNet.AI.csproj
#:property TreatWarningsAsErrors=false

using ScrapyNet.AI;
using ScrapyNet.Sandbox;
using ScrapyNet;

static void display(object? value) => Console.WriteLine(value is System.Collections.IEnumerable e && value is not string ? string.Join("\n", e.Cast<object?>()) : value);


var site = await SandboxSite.StartAsync();
var kb = new KnowledgeBase(new HashingEmbeddingGenerator(512), chunking: new ChunkingOptions { MaxWords = 120, OverlapWords = 20 });
var settings = new Settings();
settings.Set(SettingKeys.LogLevel, "WARNING");
settings.ItemPipelines.Add(new RagIngestionPipeline(kb) { Summarizer = new ExtractiveSummarizer() }, 800);
await Scrapy.CrawlAsync(new NewsSpider(site.Url("/news/")), settings);
display($"{kb.Stats.Documents} documents, {kb.Stats.Chunks} chunks, {kb.Stats.NearDuplicates} near-duplicate skipped");
var hits = await kb.SearchAsync("how do crawlers avoid proxy bans?", top: 3);
display(hits.Select(h => $"{h.Score:0.000}  {h.Record.Metadata["title"]}"));
if (Environment.GetEnvironmentVariable("SCRAPYNET_DEEPSEEK_KEY") is { } key)
{
    var withModel = new KnowledgeBase(kb.Embeddings, kb.Store, kb.Chunking)
    {
        LanguageModel = new OpenAiChatModel("deepseek-v4-flash", key, "https://api.deepseek.com/v1/"),
    };
    var answer = await withModel.AskAsync("What does proxy rotation do when a proxy gets banned?");
    display(answer.Answer);
}
await site.DisposeAsync();

public sealed class NewsSpider(string url) : Spider
{
    public override IReadOnlyList<string> StartUrls => [url];

    public override async IAsyncEnumerable<object> Parse(Response response)
    {
        foreach (var r in response.FollowAllCss("article.teaser h2 a", Article)) yield return r;
        await Task.CompletedTask;
    }

    private IEnumerable<object> Article(Response r)
    {
        yield return new Dictionary<string, object?> { ["url"] = r.Url, ["html"] = r.Text };
    }
}
