// Generated by tools/notebooks/build.mjs from notebooks/06-platform-jobs.ipynb — do not edit.
#:project ../../../src/ScrapyNet.Core/ScrapyNet.Core.csproj
#:project ../../../src/ScrapyNet.Sandbox/ScrapyNet.Sandbox.csproj
#:project ../../../src/ScrapyNet.Platform/ScrapyNet.Platform.csproj
#:property TreatWarningsAsErrors=false

using ScrapyNet.Platform;
using ScrapyNet.Sandbox;
using ScrapyNet;

static void display(object? value) => Console.WriteLine(value is System.Collections.IEnumerable e && value is not string ? string.Join("\n", e.Cast<object?>()) : value);


var site = await SandboxSite.StartAsync();
var catalog = new SpiderCatalog();
catalog.Create(new SpiderDefinition
{
    Id = "books",
    Name = "books",
    Target = new TargetConfig { StartUrls = [site.Url("/books/")] },
    Rules = new ScrapingRules
    {
        DetailLinks = ["article.product_pod h3 a"],
        FollowLinks = ["li.next a"],
        Fields = new()
        {
            ["title"] = new FieldRule { Css = "h1::text", Processors = ["clean"] },
            ["price"] = new FieldRule { Css = "p.price_color::text", Processors = ["price"] },
        },
    },
});
display(catalog.List().Select(d => $"{d.Id} v{d.Version} declarative={d.IsDeclarative}"));
var jobs = new JobManager(catalog, new JobManagerOptions
{
    BaseSettings = () => { var s = new Settings(); s.Set(SettingKeys.LogLevel, "WARNING"); return s; },
});
var monitor = new CrawlMonitor(jobs);
var alerts = new List<Alert>();
new NotificationDispatcher(jobs).Route(new CallbackNotifier(a => { alerts.Add(a); return Task.CompletedTask; }), AlertSeverity.Info);

var job = await jobs.WaitAsync(jobs.RunNow("books").Id);
display($"{job.Status}: {job.ItemCount} items, {job.ResponseCount} responses in {job.Duration?.TotalSeconds:0.00}s");
display(alerts);
var cron = new CronExpression(Schedules.Weekly(DayOfWeek.Monday, 6, 30));
display(cron.GetOccurrences(DateTimeOffset.UtcNow, 3).Select(t => t.ToString("ddd yyyy-MM-dd HH:mm")));

var metrics = monitor.Get(job.Id)!;
display($"requests={metrics.Requests} responses={metrics.Responses} items={metrics.Items} errorRate={metrics.ErrorRate:P1}");
await site.DisposeAsync();

