// Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ActorNet.Generators;

/// <summary>
/// Turns an interface marked <c>[ActorInterface]</c> into the messages, proxy and actor base that
/// would otherwise be written by hand.
/// </summary>
/// <remarks>
/// <para>
/// The hand-written form has three things that have to agree - the request type, the response type
/// and the handler - and nothing that checks they do. Generating all three from one declaration is
/// what turns a mismatch from an ask timing out in production into a compile error.
/// </para>
/// <para>
/// Nothing exotic is emitted: the records carry the same <c>[ActorMessage]</c> alias a hand-written
/// message would, and the proxy calls the same <c>TellAsync</c> and <c>AskAsync</c>. A generated
/// call across a node boundary is byte-for-byte the traffic the manual version produced.
/// </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class ActorInterfaceGenerator : IIncrementalGenerator
{
    private const string AttributeName = "ActorNet.ActorInterfaceAttribute";

    private static readonly DiagnosticDescriptor MustReturnTask = new(
        "ACTORNET001",
        "An actor interface method must return Task or ValueTask",
        "'{0}' returns '{1}'. An actor call is a message and a reply, so it has to be awaitable: use Task, Task<T>, ValueTask or ValueTask<T>.",
        "ActorNet", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NoByRefParameters = new(
        "ACTORNET002",
        "An actor interface method cannot take a parameter by reference",
        "'{0}' takes '{1}' by reference. Parameters become fields of a message that may cross a process boundary, where a reference means nothing.",
        "ActorNet", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NoGenericMethods = new(
        "ACTORNET003",
        "An actor interface method cannot be generic",
        "'{0}' is generic. The message type would have to be chosen at the call site and registered before it exists, which the type allow-list cannot do.",
        "ActorNet", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NoProperties = new(
        "ACTORNET004",
        "An actor interface cannot declare properties or events",
        "'{0}' declares '{1}'. An actor is reached by messages; a property would read as synchronous access to state that lives on another thread, and possibly another machine.",
        "ActorNet", DiagnosticSeverity.Error, isEnabledByDefault: true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var interfaces = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(interfaces, static (source, symbol) => Emit(source, symbol));
    }

    private static void Emit(SourceProductionContext context, INamedTypeSymbol iface)
    {
        var model = ActorInterfaceModel.From(iface, context);
        if (model is null) return;

        var text = Render(model);
        context.AddSource($"{model.BaseName}.ActorNet.g.cs", SourceText.From(text, Encoding.UTF8));
    }

    private static string Render(ActorInterfaceModel model)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/>");
        w.Line("// Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.");
        w.Line("#nullable enable");
        w.Line();
        w.Line("using System;");
        w.Line("using System.Threading;");
        w.Line("using System.Threading.Tasks;");
        w.Line("using ActorNet;");
        w.Line("using ActorNet.Serialization;");
        w.Line();

        var scoped = model.Namespace is not null;
        if (scoped)
        {
            w.Line($"namespace {model.Namespace}");
            w.Line("{");
            w.Indent();
        }

        RenderMessages(w, model);
        RenderProxy(w, model);
        RenderActorBase(w, model);
        RenderProtocol(w, model);

        if (scoped)
        {
            w.Outdent();
            w.Line("}");
        }

        return w.ToString();
    }

    private static void RenderMessages(CodeWriter w, ActorInterfaceModel model)
    {
        foreach (var method in model.Methods)
        {
            var parameters = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));

            w.Line($"/// <summary>The <c>{model.Interface}.{method.Name}</c> call, as a message.</summary>");
            w.Line($"[ActorMessage(Alias = \"{model.Alias}.{method.AliasSegment}\")]");
            w.Line($"public sealed record {method.RequestType}({parameters});");
            w.Line();

            if (!method.HasResult) continue;

            w.Line($"/// <summary>What <c>{model.Interface}.{method.Name}</c> answered.</summary>");
            w.Line($"[ActorMessage(Alias = \"{model.Alias}.{method.AliasSegment}.reply\")]");
            w.Line($"public sealed record {method.ReplyType}({method.ResultType} Value);");
            w.Line();
        }
    }

    private static void RenderProxy(CodeWriter w, ActorInterfaceModel model)
    {
        w.Line($"/// <summary>Addresses a <c>{model.Interface}</c> by key, wherever in the cluster it lives.</summary>");
        w.Line($"public static class {model.BaseName}Proxy");
        w.Line("{");
        w.Indent();
        w.Line("/// <summary>The actor with this key, as an interface the compiler can check calls against.</summary>");
        w.Line("/// <remarks>");
        w.Line("/// The implementing type is named because an actor address is its type name and its key, and");
        w.Line("/// an interface does not know which actor implements it. The constraint is what stops it");
        w.Line("/// being pointed at an actor that does not speak this protocol.");
        w.Line("/// </remarks>");
        w.Line($"public static {model.Interface} Of<TActor>(IActorSystem system, string key)");
        w.Indent();
        w.Line($"where TActor : {model.BaseName}ActorBase");
        w.Outdent();
        w.Line("{");
        w.Indent();
        w.Line("ArgumentNullException.ThrowIfNull(system);");
        w.Line("ArgumentException.ThrowIfNullOrEmpty(key);");
        w.Line();
        w.Line("return new Client(system, ActorId.For<TActor>(key));");
        w.Outdent();
        w.Line("}");
        w.Line();
        w.Line("/// <summary>The actor with this exact address.</summary>");
        w.Line($"public static {model.Interface} At(IActorSystem system, ActorId id)");
        w.Line("{");
        w.Indent();
        w.Line("ArgumentNullException.ThrowIfNull(system);");
        w.Line($"return new Client(system, id);");
        w.Outdent();
        w.Line("}");
        w.Line();

        w.Line($"private sealed class Client(IActorSystem system, ActorId id) : {model.Interface}");
        w.Line("{");
        w.Indent();

        foreach (var method in model.Methods)
        {
            var signature = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}")
                .Concat(method.HasCancellationToken ? new[] { "CancellationToken cancellationToken = default" } : Array.Empty<string>()));

            var arguments = string.Join(", ", method.Parameters.Select(p => p.Name));
            var token = method.HasCancellationToken ? "cancellationToken" : "default";

            w.Line($"public {method.ReturnType} {method.Name}({signature})");
            w.Line("{");
            w.Indent();

            if (method.HasResult)
            {
                w.Line($"var request = new {method.RequestType}({arguments});");
                w.Line($"{(method.ReturnsValueTask ? "return new(Ask());" : "return Ask();")}");
                w.Line();
                w.Line($"async Task<{method.ResultType}> Ask()");
                w.Line("{");
                w.Indent();
                w.Line($"var reply = await system.AskAsync<{method.ReplyType}>(id, request, {model.TimeoutExpression}, {token}).ConfigureAwait(false);");
                w.Line("return reply.Value;");
                w.Outdent();
                w.Line("}");
            }
            else
            {
                // A tell, not an ask: the interface promises the message was accepted, which is
                // exactly what TellAsync completes on. Waiting for the handler would be a
                // different promise and a much more expensive one.
                w.Line($"var request = new {method.RequestType}({arguments});");
                if (method.ReturnsValueTask)
                    w.Line($"return system.TellAsync(id, request, default, {token});");
                else
                    w.Line($"return system.TellAsync(id, request, default, {token}).AsTask();");
            }

            w.Outdent();
            w.Line("}");
            w.Line();
        }

        w.Outdent();
        w.Line("}");
        w.Outdent();
        w.Line("}");
        w.Line();
    }

    private static void RenderActorBase(CodeWriter w, ActorInterfaceModel model)
    {
        w.Line($"/// <summary>Routes <c>{model.Interface}</c> messages to its methods. Derive an actor from this.</summary>");
        w.Line("/// <remarks>");
        w.Line("/// The handlers are registered in the constructor, so an implementation only has to write the");
        w.Line("/// methods. Anything the interface does not cover is still reachable by overriding");
        w.Line("/// <c>ReceiveAsync</c> or registering more handlers of its own.");
        w.Line("/// </remarks>");
        w.Line($"public abstract class {model.BaseName}ActorBase : ReceiveActor, {model.Interface}");
        w.Line("{");
        w.Indent();
        w.Line($"protected {model.BaseName}ActorBase()");
        w.Line("{");
        w.Indent();

        foreach (var method in model.Methods)
        {
            var arguments = string.Join(", ", method.Parameters.Select(p => $"m.{p.Name}"));
            var call = method.HasCancellationToken
                ? $"{method.Name}({(arguments.Length > 0 ? arguments + ", " : string.Empty)}ct)"
                : $"{method.Name}({arguments})";

            if (method.HasResult)
            {
                w.Line($"On<{method.RequestType}>(async (m, ct) =>");
                w.Line("{");
                w.Indent();
                w.Line($"var result = await {call}.ConfigureAwait(false);");
                w.Line($"await Context.ReplyAsync(new {method.ReplyType}(result), ct).ConfigureAwait(false);");
                w.Outdent();
                w.Line("});");
            }
            else
            {
                w.Line($"On<{method.RequestType}>(async (m, ct) => await {call}.ConfigureAwait(false));");
            }
        }

        w.Outdent();
        w.Line("}");
        w.Line();

        foreach (var method in model.Methods)
        {
            var signature = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}")
                .Concat(method.HasCancellationToken ? new[] { "CancellationToken cancellationToken = default" } : Array.Empty<string>()));

            w.Line($"/// <inheritdoc cref=\"{model.Interface}.{method.Name}\" />");
            w.Line($"public abstract {method.ReturnType} {method.Name}({signature});");
            w.Line();
        }

        w.Outdent();
        w.Line("}");
        w.Line();
    }

    private static void RenderProtocol(CodeWriter w, ActorInterfaceModel model)
    {
        w.Line($"/// <summary>Registers every message <c>{model.Interface}</c> generates.</summary>");
        w.Line("/// <remarks>");
        w.Line("/// Every node that sends or receives these has to have them on its allow-list, so this is");
        w.Line("/// called on both sides. Forgetting it fails loudly at the first message rather than quietly.");
        w.Line("/// </remarks>");
        w.Line($"public static class {model.BaseName}Protocol");
        w.Line("{");
        w.Indent();
        w.Line("/// <summary>Registers the messages. For a node that calls this actor without hosting it.</summary>");
        w.Line("public static IActorSystem Register(IActorSystem system)");
        w.Line("{");
        w.Indent();
        w.Line("ArgumentNullException.ThrowIfNull(system);");

        foreach (var method in model.Methods)
        {
            w.Line($"system.RegisterMessage<{method.RequestType}>();");
            if (method.HasResult) w.Line($"system.RegisterMessage<{method.ReplyType}>();");
        }

        w.Line("return system;");
        w.Outdent();
        w.Line("}");
        w.Line();
        w.Line("/// <summary>Registers the messages and the actor that implements them.</summary>");
        w.Line("/// <remarks>");
        w.Line("/// The two halves are separate because a node that only calls this actor still needs its");
        w.Line("/// messages on the allow-list, and registering an actor type it will never host would make");
        w.Line("/// the ring believe it can own those keys.");
        w.Line("/// </remarks>");
        w.Line("public static IActorSystem Register<TActor>(IActorSystem system)");
        w.Indent();
        w.Line($"where TActor : {model.BaseName}ActorBase");
        w.Outdent();
        w.Line("{");
        w.Indent();
        w.Line("Register(system);");
        w.Line("return system.RegisterActor<TActor>();");
        w.Outdent();
        w.Line("}");
        w.Outdent();
        w.Line("}");
    }

    /// <summary>What the generator needs to know about one interface, once it is known to be valid.</summary>
    private sealed class ActorInterfaceModel
    {
        public string Interface { get; private set; } = string.Empty;
        public string BaseName { get; private set; } = string.Empty;
        public string Alias { get; private set; } = string.Empty;
        public string? Namespace { get; private set; }
        public string TimeoutExpression { get; private set; } = "null";
        public List<MethodModel> Methods { get; } = new();

        public static ActorInterfaceModel? From(INamedTypeSymbol iface, SourceProductionContext context)
        {
            var attribute = iface.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttributeName);

            var baseName = iface.Name.Length > 1 && iface.Name[0] == 'I' && char.IsUpper(iface.Name[1])
                ? iface.Name.Substring(1)
                : iface.Name;

            var alias = attribute?.NamedArguments.FirstOrDefault(a => a.Key == "Alias").Value.Value as string;
            var timeout = attribute?.NamedArguments.FirstOrDefault(a => a.Key == "TimeoutSeconds").Value.Value as int?;

            var model = new ActorInterfaceModel
            {
                Interface = iface.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                BaseName = baseName,
                Alias = string.IsNullOrWhiteSpace(alias) ? Camel(baseName) : alias!,
                Namespace = iface.ContainingNamespace.IsGlobalNamespace ? null : iface.ContainingNamespace.ToDisplayString(),
                TimeoutExpression = timeout is > 0 ? $"TimeSpan.FromSeconds({timeout})" : "null",
            };

            var ok = true;

            foreach (var member in iface.GetMembers())
            {
                if (member is IPropertySymbol or IEventSymbol)
                {
                    context.ReportDiagnostic(Diagnostic.Create(NoProperties, member.Locations.FirstOrDefault(), iface.Name, member.Name));
                    ok = false;
                    continue;
                }

                if (member is not IMethodSymbol method || method.MethodKind != MethodKind.Ordinary) continue;

                var built = MethodModel.From(method, baseName, context);
                if (built is null) ok = false;
                else model.Methods.Add(built);
            }

            return ok ? model : null;
        }

        private static string Camel(string value) =>
            value.Length == 0 ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);
    }

    /// <summary>One interface method, reduced to what the emitted code needs.</summary>
    private sealed class MethodModel
    {
        public string Name { get; private set; } = string.Empty;
        public string RequestType { get; private set; } = string.Empty;
        public string ReplyType { get; private set; } = string.Empty;
        public string AliasSegment { get; private set; } = string.Empty;
        public string ReturnType { get; private set; } = string.Empty;
        public string ResultType { get; private set; } = string.Empty;
        public bool HasResult { get; private set; }
        public bool ReturnsValueTask { get; private set; }
        public bool HasCancellationToken { get; private set; }
        public List<ParameterModel> Parameters { get; } = new();

        public static MethodModel? From(IMethodSymbol method, string baseName, SourceProductionContext context)
        {
            if (method.IsGenericMethod)
            {
                context.ReportDiagnostic(Diagnostic.Create(NoGenericMethods, method.Locations.FirstOrDefault(), method.Name));
                return null;
            }

            var returnType = method.ReturnType as INamedTypeSymbol;
            var returnName = returnType?.ConstructedFrom.ToDisplayString() ?? method.ReturnType.ToDisplayString();

            var isTask = returnName is "System.Threading.Tasks.Task" or "System.Threading.Tasks.ValueTask";
            var isTaskOf = returnName is "System.Threading.Tasks.Task<TResult>" or "System.Threading.Tasks.ValueTask<TResult>";

            if (!isTask && !isTaskOf)
            {
                context.ReportDiagnostic(Diagnostic.Create(MustReturnTask, method.Locations.FirstOrDefault(),
                    method.Name, method.ReturnType.ToDisplayString()));
                return null;
            }

            // A trailing CancellationToken is a call-site concern, not part of the message: it
            // bounds the wait for a reply and has no meaning once the request is on the wire.
            var parameters = method.Parameters.ToList();
            var hasToken = parameters.Count > 0 &&
                parameters[parameters.Count - 1].Type.ToDisplayString() == "System.Threading.CancellationToken";

            if (hasToken) parameters.RemoveAt(parameters.Count - 1);

            var model = new MethodModel
            {
                Name = method.Name,
                Trimmed = TrimAsync(method.Name),
                HasResult = isTaskOf,
                ReturnsValueTask = returnName.StartsWith("System.Threading.Tasks.ValueTask", StringComparison.Ordinal),
                HasCancellationToken = hasToken,
                ReturnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                ResultType = isTaskOf ? returnType!.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat) : "void",
            };

            model.RequestType = $"{baseName}{model.Trimmed}Request";
            model.ReplyType = $"{baseName}{model.Trimmed}Reply";
            model.AliasSegment = Camel(model.Trimmed);

            foreach (var parameter in parameters)
            {
                if (parameter.RefKind != RefKind.None)
                {
                    context.ReportDiagnostic(Diagnostic.Create(NoByRefParameters, parameter.Locations.FirstOrDefault(),
                        method.Name, parameter.Name));
                    return null;
                }

                model.Parameters.Add(new ParameterModel
                {
                    // Capitalised, because these become record properties, and a record positional
                    // parameter named in camelCase would generate a property that breaks convention.
                    Name = Pascal(parameter.Name),
                    Type = parameter.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat),
                });
            }

            return model;
        }

        private string Trimmed { get; set; } = string.Empty;

        /// <summary>Drops a trailing <c>Async</c>, so the message is not called <c>DepositAsyncRequest</c>.</summary>
        private static string TrimAsync(string name) =>
            name.EndsWith("Async", StringComparison.Ordinal) && name.Length > 5
                ? name.Substring(0, name.Length - 5)
                : name;

        private static string Camel(string value) =>
            value.Length == 0 ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);

        private static string Pascal(string value) =>
            value.Length == 0 ? value : char.ToUpperInvariant(value[0]) + value.Substring(1);
    }

    private sealed class ParameterModel
    {
        public string Name { get; set; } = string.Empty;
        public string Type { get; set; } = string.Empty;
    }

    /// <summary>A very small indenting writer, so the generated file reads like hand-written code.</summary>
    private sealed class CodeWriter
    {
        private readonly StringBuilder _builder = new();
        private int _depth;

        public void Indent() => _depth++;
        public void Outdent() => _depth = Math.Max(0, _depth - 1);

        public void Line(string? text = null)
        {
            if (string.IsNullOrEmpty(text))
            {
                _builder.AppendLine();
                return;
            }

            _builder.Append(new string(' ', _depth * 4)).AppendLine(text);
        }

        public override string ToString() => _builder.ToString();
    }
}
