// APL.Net - Another Parallel Library for .NET
// Dibuat oleh Gravicode Studios, dipimpin oleh Kang Fadhil.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace AplNet.SourceGen;

/// <summary>
/// Turns <c>[AplBody]</c> / <c>[AplRangeBody]</c> static methods into struct loop bodies plus a
/// factory method on <c>AplNet.AplGen</c>.
/// </summary>
/// <remarks>
/// For
/// <code>
/// [AplBody] internal static void Scale(int i, double[] data, double factor) =&gt; data[i] *= factor;
/// </code>
/// it emits a <c>readonly struct</c> implementing <c>IWorkBody</c> whose fields are
/// <c>data</c> and <c>factor</c> and whose <c>Invoke(int)</c> calls <c>Scale</c>, and a factory
/// <c>AplGen.Scale(double[] data, double factor)</c>. The struct is what makes the call zero-alloc and
/// inlinable; the generator only saves writing it.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class AplBodyGenerator : IIncrementalGenerator
{
    private const string ElementAttribute = "AplNet.AplBodyAttribute";
    private const string RangeAttribute = "AplNet.AplRangeBodyAttribute";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<BodyModel> elements = context.SyntaxProvider.ForAttributeWithMetadataName(
            ElementAttribute,
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, ct) => BodyModel.Create(ctx, isRange: false, ct));

        IncrementalValuesProvider<BodyModel> ranges = context.SyntaxProvider.ForAttributeWithMetadataName(
            RangeAttribute,
            static (node, _) => node is MethodDeclarationSyntax,
            static (ctx, ct) => BodyModel.Create(ctx, isRange: true, ct));

        IncrementalValueProvider<(ImmutableArray<BodyModel> Left, ImmutableArray<BodyModel> Right)> all =
            elements.Collect().Combine(ranges.Collect());

        context.RegisterSourceOutput(all, static (spc, pair) => Emit(spc, pair.Left.AddRange(pair.Right)));
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<BodyModel> models)
    {
        var valid = new List<BodyModel>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var structNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (BodyModel model in models.OrderBy(m => m.SortKey, StringComparer.Ordinal))
        {
            if (model.Error is { } error)
            {
                context.ReportDiagnostic(error.ToDiagnostic());
                continue;
            }

            // Two bodies whose factories would have the same name and parameter types cannot both be
            // AplGen members; say so on the second one rather than emitting code that does not compile.
            string signature = model.MethodName + "(" + string.Join(",", model.Captures.Select(c => c.Type)) + ")";
            if (!seen.Add(signature))
            {
                context.ReportDiagnostic(Diagnostic.Create(Descriptors.DuplicateFactory, model.Location.ToLocation(), model.MethodName));
                continue;
            }

            // Overloads of one method share a base struct name; number the later ones.
            string structName = model.StructName;
            for (int n = 2; !structNames.Add(structName); n++)
                structName = model.StructName + "_" + n;

            valid.Add(model with { StructName = structName });
        }

        if (valid.Count == 0)
            return;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/> by APL.Net.SourceGen");
        source.AppendLine("#nullable enable");
        source.AppendLine("#pragma warning disable CS1591");
        source.AppendLine();
        source.AppendLine("namespace AplNet");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>Factories for the loop bodies generated from [AplBody] and [AplRangeBody] methods.</summary>");
        source.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"APL.Net.SourceGen\", \"1.0.0\")]");
        source.AppendLine("    internal static partial class AplGen");
        source.AppendLine("    {");
        foreach (BodyModel model in valid)
        {
            string parameters = string.Join(", ", model.Captures.Select(c => c.Type + " @" + c.Name));
            string arguments = string.Join(", ", model.Captures.Select(c => "@" + c.Name));
            source.AppendLine($"        /// <summary>A struct body that calls <c>{Escape(model.MethodDisplay)}</c>.</summary>");
            source.AppendLine($"        public static global::AplNet.Generated.{model.StructName} {model.MethodName}({parameters}) => new global::AplNet.Generated.{model.StructName}({arguments});");
        }

        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("namespace AplNet.Generated");
        source.AppendLine("{");
        foreach (BodyModel model in valid)
            EmitStruct(source, model);
        source.AppendLine("}");

        context.AddSource("AplGen.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void EmitStruct(StringBuilder source, BodyModel model)
    {
        string iface = model.IsRange ? "global::AplNet.Core.IRangeWorkBody" : "global::AplNet.Core.IWorkBody";
        source.AppendLine($"    /// <summary>Generated loop body for <c>{Escape(model.MethodDisplay)}</c>.</summary>");
        source.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"APL.Net.SourceGen\", \"1.0.0\")]");
        source.AppendLine($"    internal readonly struct {model.StructName} : {iface}");
        source.AppendLine("    {");

        foreach (CaptureModel capture in model.Captures)
            source.AppendLine($"        private readonly {capture.Type} _{capture.Name};");

        if (model.Captures.Count > 0)
        {
            source.AppendLine();
            string parameters = string.Join(", ", model.Captures.Select(c => c.Type + " @" + c.Name));
            source.AppendLine($"        public {model.StructName}({parameters})");
            source.AppendLine("        {");
            foreach (CaptureModel capture in model.Captures)
                source.AppendLine($"            _{capture.Name} = @{capture.Name};");
            source.AppendLine("        }");
        }

        source.AppendLine();
        string fields = string.Concat(model.Captures.Select(c => ", _" + c.Name));
        source.AppendLine("        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
        if (model.IsRange)
            source.AppendLine($"        public void Invoke(int fromInclusive, int toExclusive) => {model.ContainingType}.{model.MethodName}(fromInclusive, toExclusive{fields});");
        else
            source.AppendLine($"        public void Invoke(int index) => {model.ContainingType}.{model.MethodName}(index{fields});");

        source.AppendLine("    }");
        source.AppendLine();
    }

    private static string Escape(string text) => text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}

/// <summary>Everything the emitter needs about one attributed method. Equatable, so the pipeline caches.</summary>
internal sealed record BodyModel(
    string MethodName,
    string MethodDisplay,
    string ContainingType,
    string StructName,
    bool IsRange,
    EquatableArray<CaptureModel> Captures,
    LocationInfo Location,
    DiagnosticInfo? Error)
{
    public string SortKey => ContainingType + "." + MethodName + "/" + Location.Span.Start;

    public static BodyModel Create(GeneratorAttributeSyntaxContext context, bool isRange, CancellationToken cancellationToken)
    {
        var method = (IMethodSymbol)context.TargetSymbol;
        var syntax = (MethodDeclarationSyntax)context.TargetNode;
        LocationInfo location = LocationInfo.From(syntax.Identifier.GetLocation());
        string display = method.ToDisplayString(SymbolDisplayFormat.CSharpShortErrorMessageFormat);
        string containing = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string structName = "__" + Sanitize(method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "")) + "_" + method.Name + "_Generated";

        BodyModel Fail(DiagnosticDescriptor descriptor, params string[] args) =>
            new(method.Name, display, containing, structName, isRange, EquatableArray<CaptureModel>.Empty, location, new DiagnosticInfo(descriptor.Id, location, args));

        cancellationToken.ThrowIfCancellationRequested();

        if (!method.IsStatic)
            return Fail(Descriptors.MustBeStatic, method.Name);
        if (!method.ReturnsVoid)
            return Fail(Descriptors.MustReturnVoid, method.Name);
        if (method.IsGenericMethod || IsInGenericType(method.ContainingType))
            return Fail(Descriptors.NoGenerics, method.Name);
        if (!IsAccessible(method))
            return Fail(Descriptors.MustBeAccessible, method.Name);

        int indexParameters = isRange ? 2 : 1;
        if (method.Parameters.Length < indexParameters ||
            method.Parameters.Take(indexParameters).Any(p => p.Type.SpecialType != SpecialType.System_Int32 || p.RefKind != RefKind.None))
        {
            return Fail(isRange ? Descriptors.RangeSignature : Descriptors.ElementSignature, method.Name);
        }

        var captures = new List<CaptureModel>();
        foreach (IParameterSymbol parameter in method.Parameters.Skip(indexParameters))
        {
            if (parameter.RefKind != RefKind.None || parameter.Type.IsRefLikeType || parameter.IsParams)
                return Fail(Descriptors.UnsupportedParameter, method.Name, parameter.Name);

            string type = parameter.Type.ToDisplayString(
                SymbolDisplayFormat.FullyQualifiedFormat.AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
            captures.Add(new CaptureModel(parameter.Name, type));
        }

        return new BodyModel(method.Name, display, containing, structName, isRange, new EquatableArray<CaptureModel>(captures.ToArray()), location, null);
    }

    private static bool IsInGenericType(INamedTypeSymbol? type)
    {
        for (; type is not null; type = type.ContainingType)
        {
            if (type.IsGenericType)
                return true;
        }

        return false;
    }

    /// <summary>The generated struct lives outside the method's type, so the method and every enclosing type must be reachable from the assembly.</summary>
    private static bool IsAccessible(IMethodSymbol method)
    {
        if (!IsAssemblyVisible(method.DeclaredAccessibility))
            return false;
        for (INamedTypeSymbol? type = method.ContainingType; type is not null; type = type.ContainingType)
        {
            if (!IsAssemblyVisible(type.DeclaredAccessibility))
                return false;
        }

        return true;
    }

    private static bool IsAssemblyVisible(Accessibility accessibility) =>
        accessibility is Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal;

    private static string Sanitize(string name)
    {
        var builder = new StringBuilder(name.Length);
        foreach (char c in name)
            builder.Append(char.IsLetterOrDigit(c) ? c : '_');
        return builder.ToString();
    }
}

internal sealed record CaptureModel(string Name, string Type);

/// <summary>A location that compares by value, so it can live in a cached model.</summary>
internal sealed record LocationInfo(string FilePath, TextSpan Span, LinePositionSpan LineSpan)
{
    public static LocationInfo From(Location location) =>
        new(location.SourceTree?.FilePath ?? string.Empty, location.SourceSpan, location.GetLineSpan().Span);

    public Location ToLocation() => Location.Create(FilePath, Span, LineSpan);
}

internal sealed record DiagnosticInfo(string Id, LocationInfo Location, EquatableArray<string> Arguments)
{
    public DiagnosticInfo(string id, LocationInfo location, string[] arguments)
        : this(id, location, new EquatableArray<string>(arguments))
    {
    }

    public Diagnostic ToDiagnostic() =>
        Diagnostic.Create(Descriptors.ById(Id), Location.ToLocation(), Arguments.ToArray());
}

/// <summary>An immutable array with value equality.</summary>
internal readonly struct EquatableArray<T> : IEquatable<EquatableArray<T>>
    where T : IEquatable<T>
{
    public static readonly EquatableArray<T> Empty = new([]);

    private readonly T[]? _items;

    public EquatableArray(T[] items) => _items = items;

    public int Count => _items?.Length ?? 0;

    public T[] ToArray() => _items is null ? [] : (T[])_items.Clone();

    public IEnumerator<T> GetEnumerator() => ((IEnumerable<T>)(_items ?? [])).GetEnumerator();

    public IEnumerable<TResult> Select<TResult>(Func<T, TResult> selector) => (_items ?? []).Select(selector);

    public bool Equals(EquatableArray<T> other) => (_items ?? []).AsSpan().SequenceEqual(other._items ?? []);

    public override bool Equals(object? obj) => obj is EquatableArray<T> other && Equals(other);

    public override int GetHashCode()
    {
        int hash = 17;
        foreach (T item in _items ?? [])
            hash = unchecked(hash * 31 + (item?.GetHashCode() ?? 0));
        return hash;
    }
}

internal static class Descriptors
{
    private const string Category = "APL.Net";

    public static readonly DiagnosticDescriptor MustBeStatic = new(
        "APL001", "Loop body must be static",
        "Method '{0}' is marked as an APL.Net loop body but is not static", Category, DiagnosticSeverity.Error, true);

    public static readonly DiagnosticDescriptor MustReturnVoid = new(
        "APL002", "Loop body must return void",
        "Method '{0}' is marked as an APL.Net loop body but does not return void", Category, DiagnosticSeverity.Error, true);

    public static readonly DiagnosticDescriptor ElementSignature = new(
        "APL003", "Loop body must take the index first",
        "Method '{0}' is marked [AplBody] but its first parameter is not 'int index'", Category, DiagnosticSeverity.Error, true);

    public static readonly DiagnosticDescriptor RangeSignature = new(
        "APL004", "Range body must take the range first",
        "Method '{0}' is marked [AplRangeBody] but its first two parameters are not 'int fromInclusive, int toExclusive'", Category, DiagnosticSeverity.Error, true);

    public static readonly DiagnosticDescriptor NoGenerics = new(
        "APL005", "Loop body cannot be generic",
        "Method '{0}' is generic or declared in a generic type, which the generated body cannot name", Category, DiagnosticSeverity.Error, true);

    public static readonly DiagnosticDescriptor MustBeAccessible = new(
        "APL006", "Loop body must be internal or public",
        "Method '{0}' or a type containing it is private or protected; the generated body lives outside it and cannot call it", Category, DiagnosticSeverity.Error, true);

    public static readonly DiagnosticDescriptor UnsupportedParameter = new(
        "APL007", "Unsupported captured parameter",
        "Parameter '{1}' of '{0}' is ref/out/in, params, or a ref struct (such as Span<T>), and cannot be stored in the generated body; pass an array or Memory<T> instead", Category, DiagnosticSeverity.Error, true);

    public static readonly DiagnosticDescriptor DuplicateFactory = new(
        "APL008", "Duplicate loop body factory",
        "Another loop body already generates AplGen.{0} with the same parameter types; rename one of the methods", Category, DiagnosticSeverity.Error, true);

    public static DiagnosticDescriptor ById(string id) => id switch
    {
        "APL001" => MustBeStatic,
        "APL002" => MustReturnVoid,
        "APL003" => ElementSignature,
        "APL004" => RangeSignature,
        "APL005" => NoGenerics,
        "APL006" => MustBeAccessible,
        "APL007" => UnsupportedParameter,
        _ => DuplicateFactory,
    };
}
