<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AplNet.Samples</RootNamespace>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/APL.Net/APL.Net.csproj" />
    <ProjectReference Include="../../src/APL.Net.SourceGen/APL.Net.SourceGen.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
